import { Product, Category } from '@/types';

export const categories: Category[] = [
  {
    id: 'women',
    name: 'Qadın Geyimləri',
    slug: 'women',
    subcategories: [
      { id: 'women-tops', name: 'Üst Geyimlər', slug: 'women-tops' },
      { id: 'women-bottoms', name: 'Aşağı Geyimlər', slug: 'women-bottoms' },
      { id: 'women-dresses', name: 'Paltarlar', slug: 'women-dresses' },
      { id: 'women-outerwear', name: 'Xarici Geyimlər', slug: 'women-outerwear' },
      { id: 'women-accessories', name: 'Aksesuarlar', slug: 'women-accessories' },
      { id: 'women-shoes', name: 'Ayaqqabılar', slug: 'women-shoes' },
      { id: 'women-lingerie', name: 'İç Geyimlər', slug: 'women-lingerie' },
    ],
  },
  {
    id: 'men',
    name: 'Kişi Geyimləri',
    slug: 'men',
    subcategories: [
      { id: 'men-tops', name: 'Üst Geyimlər', slug: 'men-tops' },
      { id: 'men-bottoms', name: 'Aşağı Geyimlər', slug: 'men-bottoms' },
      { id: 'men-outerwear', name: 'Xarici Geyimlər', slug: 'men-outerwear' },
      { id: 'men-accessories', name: 'Aksesuarlar', slug: 'men-accessories' },
      { id: 'men-shoes', name: 'Ayaqqabılar', slug: 'men-shoes' },
      { id: 'men-underwear', name: 'İç Geyimlər', slug: 'men-underwear' },
    ],
  },
  {
    id: 'kids',
    name: 'Uşaq Geyimləri',
    slug: 'kids',
    subcategories: [
      { id: 'kids-0-2', name: '0-2 Yaş', slug: 'kids-0-2' },
      { id: 'kids-3-6', name: '3-6 Yaş', slug: 'kids-3-6' },
      { id: 'kids-7-12', name: '7-12 Yaş', slug: 'kids-7-12' },
      { id: 'kids-girls', name: 'Qız Geyimləri', slug: 'kids-girls' },
      { id: 'kids-boys', name: 'Oğlan Geyimləri', slug: 'kids-boys' },
      { id: 'kids-shoes', name: 'Ayaqqabılar', slug: 'kids-shoes' },
      { id: 'kids-accessories', name: 'Aksesuarlar', slug: 'kids-accessories' },
    ],
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Элегантное платье миди',
    price: 3499,
    originalPrice: 4999,
    description: 'Стильное платье миди длины из качественного материала. Идеально подходит для офиса и вечерних мероприятий.',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800'],
    category: 'women',
    subcategory: 'dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Черный', 'Белый', 'Синий'],
    material: 'Полиэстер 95%, Эластан 5%',
    brand: 'Kaiienna',
    season: 'Всесезонное',
    inStock: true,
    discount: 30,
    rating: 4.5,
    reviewsCount: 24,
  },
  {
    id: '2',
    name: 'Классическая белая рубашка',
    price: 2499,
    description: 'Универсальная белая рубашка из хлопка. Отлично сочетается с любым стилем.',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800'],
    category: 'women',
    subcategory: 'blouses',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Белый', 'Голубой'],
    material: 'Хлопок 100%',
    brand: 'Kaiienna',
    season: 'Всесезонное',
    inStock: true,
    rating: 4.8,
    reviewsCount: 18,
  },
  {
    id: '3',
    name: 'Джинсы скинни',
    price: 3999,
    description: 'Классические джинсы скинни из денима премиум качества.',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800'],
    category: 'women',
    subcategory: 'pants',
    sizes: ['24', '26', '28', '30', '32'],
    colors: ['Синий', 'Черный'],
    material: 'Хлопок 98%, Эластан 2%',
    brand: 'Kaiienna',
    season: 'Всесезонное',
    inStock: true,
    rating: 4.6,
    reviewsCount: 32,
  },
  {
    id: '4',
    name: 'Мужская футболка базового кроя',
    price: 1299,
    originalPrice: 1999,
    description: 'Комфортная футболка из мягкого хлопка. Идеальна для повседневной носки.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
    category: 'men',
    subcategory: 'tshirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Белый', 'Черный', 'Серый', 'Синий'],
    material: 'Хлопок 100%',
    brand: 'Kaiienna',
    season: 'Лето',
    inStock: true,
    discount: 35,
    rating: 4.7,
    reviewsCount: 45,
  },
  {
    id: '5',
    name: 'Мужские классические брюки',
    price: 4499,
    description: 'Элегантные классические брюки для офиса и деловых встреч.',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800'],
    category: 'men',
    subcategory: 'pants',
    sizes: ['46', '48', '50', '52', '54'],
    colors: ['Черный', 'Серый', 'Синий'],
    material: 'Шерсть 70%, Полиэстер 30%',
    brand: 'Kaiienna',
    season: 'Всесезонное',
    inStock: true,
    rating: 4.9,
    reviewsCount: 28,
  },
  {
    id: '6',
    name: 'Детское платье с цветочным принтом',
    price: 1999,
    description: 'Яркое платье для девочек с красивым цветочным принтом.',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800'],
    category: 'kids',
    subcategory: 'girls',
    sizes: ['104', '110', '116', '122', '128'],
    colors: ['Розовый', 'Голубой'],
    material: 'Хлопок 100%',
    brand: 'Kaiienna',
    season: 'Лето',
    inStock: true,
    rating: 4.8,
    reviewsCount: 15,
  },
];

export const sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '24', '26', '28', '30', '32', '46', '48', '50', '52', '54', '104', '110', '116', '122', '128'];
export const colors = ['Черный', 'Белый', 'Синий', 'Красный', 'Зеленый', 'Желтый', 'Розовый', 'Голубой', 'Серый', 'Коричневый'];
export const materials = ['Хлопок', 'Полиэстер', 'Шерсть', 'Деним', 'Шелк'];
export const brands = ['Kaiienna', 'Premium', 'Classic', 'Sport'];
export const seasons = ['Лето', 'Зима', 'Весна', 'Осень', 'Всесезонное'];

